import Head from "next/head";
import { Inter } from "next/font/google";
import Main from "./portFolio";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Krupan Shivabandhi</title>
        <link rel="shortcut icon" href="images/logo.png" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Main />
    </>
  );
}
